name: Cleanup Old Issues

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/stale@v7
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          stale-issue-message: |
            此 Issue 因长时间未有活动已被自动标记为过时。如果此 Issue 仍然有效，请在接下来 7 天内进行回复，否则将被自动关闭。
          close-issue-message: |
            此 Issue 已因长时间未有活动而自动关闭。如有需要，请重新打开或创建新的 Issue。
          days-before-stale: 30
          days-before-close: 7
          stale-label: 'stale'
          close-label: 'closed'
          exempt-issue-labels: 'pinned,important'
